SELECT i.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO i INNER JOIN REST_REVIEW r
ON i.REST_ID = r.REST_ID
WHERE SUBSTR(i.ADDRESS, 1, 2) = '서울'
GROUP BY i.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;