SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    GENDER,
    COUNT(DISTINCT i.USER_ID)
FROM USER_INFO i INNER JOIN ONLINE_SALE o
ON i.USER_ID= o.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;