SELECT APNT_NO, PT_NAME, a.PT_NO, a.MCDP_CD, DR_NAME, APNT_YMD
FROM 
    PATIENT p LEFT JOIN APPOINTMENT a ON a.PT_NO = p.PT_NO
    LEFT JOIN DOCTOR d ON a.MDDR_ID = d.DR_ID
WHERE 
    DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND
    APNT_CNCL_YN = 'N' AND 
    a.MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC;