WITH RECURSIVE _HOUR AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM _HOUR WHERE HOUR < 23 
) 
SELECT H.HOUR, COUNT(O.DATETIME)
FROM _HOUR AS H LEFT JOIN ANIMAL_OUTS O ON H.HOUR = HOUR(O.DATETIME)
GROUP BY H.HOUR;